# Generated by Django 4.1.2 on 2023-01-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lineitem',
            options={'verbose_name': 'oreder details', 'verbose_name_plural': 'orders details'},
        ),
        migrations.AddField(
            model_name='order',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
